AWSTemplateFormatVersion: '2010-09-09'
Description: "Flask-APP_sample Application(RDS only) stack"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Flask-APP-Product

  RDSDBUserName:
    Description: mysql user name
    Type: String
    Default: "admin"
  RDSDBUserPass:
    Description: mysql user password
    Type: String
    Default: "adminadmin"
    NoEcho: true
  RDSDataBaseName:
    Description: Enter the name of the database to be used in the application.
    Type: String
    Default: "sample_app_test_db"

Resources:
###RDS
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: Flask-APP-RDS
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.39
      MasterUsername: !Ref RDSDBUserName
      MasterUserPassword: !Ref RDSDBUserPass
      DBName: !Ref RDSDataBaseName
      BackupRetentionPeriod: 0
      MultiAZ: true
      PubliclyAccessible: false
      StorageType: gp2
      AllocatedStorage: 20
      StorageEncrypted: true
      CopyTagsToSnapshot: false
      DeletionProtection: false
      DeleteAutomatedBackups: true
      DBSubnetGroupName: !ImportValue Flask-App-Network-Stack-RDSSubnetGroup
      VPCSecurityGroups:
        - !ImportValue Flask-App-Security-Stack-RDSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} RDS

Outputs:
  RDSInstance:
    Description: RDS Instance
    Value: !Ref RDSInstance
    Export:
      Name: Flask-App-Application-Stack-RDSInstance
