[app_targetnode]
EC2AppInstance ansible_host=i-09bb066cda8dc2625 


[web_targetnode]
EC2WebInstance ansible_host=i-0e96e1bad6f998b58

[all:vars]
ansible_user='ec2-user'
ansible_become=true
ansible_ssh_private_key_file='~/.ssh/flask-app-project.pem'
ansible_python_interpreter=/usr/bin/python3.9
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ProxyCommand="sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\""
